version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - network

  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
      - VIRTUAL_HOST=$STAGING_URL
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

volumes:
  wordpress:
    driver_opts:
      type: none
      device: $PWD/$WORDPRESS_DIR
      o: bind
  dbdata:

networks:
  network:
    driver: bridge

